### ISSUE TITLE
Dimension type: nominal

### ISSUE THREAD

**Issue by jstcki** [zazuko/rdf-cube-schema-viz#10]
For dimensions with discrete values that have no inherent order (e.g. gender, animal species, ice cream flavors).

One question here is if this even makes sense? Ordering the values alphabetically can be inconsistent across different languages.

**Comment by ktk** [comment]
* ~For this and #9 we might want to attach a generic property to the dimension that indicates if the `sh:in` list has a clear order or not~ - does not make sense as we have that in Nominal/Ordinal definitions.

**Comment by ktk** [comment]
https://github.com/zazuko/rdf-cube-schema-viz/blob/532db871aeb61831ae08afc9697a0c7969570e99/vocab/scaleOfMeasure.ttl#L39-L43

Sample:

https://github.com/zazuko/rdf-cube-schema-viz/blob/a5de5d5593e7c499aba4a8534d7b53e184da306e/example/ubd28.ttl#L1783

**Comment by l00mi** [comment]
@herrstucki please close if all solved.
