### ISSUE TITLE
Dimension type: numerical

### ISSUE THREAD

**Issue by jstcki** [zazuko/rdf-cube-schema-viz#11]
A.k.a. what was called a measure in the old schema. Should always have a unit #4 attribute.

One special case are percentages because they are always relative to a whole. How can this be expressed? Does it need to? Is it part of the unit (e.g. "% der Gesamtbevölkerung")? Are percentage values between 0 – 100 or 0 – 1 (important for formatting the values)?

**Comment by bergos** [comment]
About the value ranges: For the use case state of charge I wanted to have values between 0-1, but percentage seemed to be the wrong unit. I did some research and my conclusion was, that the unit for that range is proportion or ratio. I couldn't find it in qudt, maybe we should make a proposal. The `conversionMultiplier` property would allow making conversions just based on numbers provided by the ontology. Anyway, I would use percentage for statistic data. In general, based on the main usage of a property I would use:

- percentage, when it will be shown directly to humans (as number or in charts)
- proportion, when it will be used for further processing/calculations (e.g. estimated battery time remaining)

**Comment by ktk** [comment]
* Check if QUDT takes care of this, if not talk to them and see if this would make sense to be included

**Comment by ktk** [comment]
Subclass of numerical in this example but would look like this:

https://github.com/zazuko/rdf-cube-schema-viz/blob/532db871aeb61831ae08afc9697a0c7969570e99/example/ubd28.ttl#L2887-L2888

**Comment by l00mi** [comment]
Covered in qudt with http://qudt.org/vocab/unit/NUM and http://qudt.org/vocab/unit/PERCENT (0-100) to be added as unit.

**Comment by l00mi** [comment]
@herrstucki please close if all solved.

**Comment by jstcki** [comment]
LGTM 👍 Will open new issue if something concrete comes up.
