### ISSUE TITLE
Dimension values/ranges

### ISSUE THREAD

**Issue by jstcki** [zazuko/rdf-cube-schema-viz#12]
How are dimension values and ranges described?

- For continuous dimensions (= numerical, temporal, geo-coordinates), include min and max value
- For discrete dimensions (= nominal, ordinal, geo-entities), include a list
  - also a count?

How can they be queried?

- As part of the metadata (shape) of a cube:
  - 👍 fast (don't need to run queries on observations)
  - 👎 a filtered subset of observations can't be expressed
  - 🤔 are long lists (e.g. baby names) an issue?
  - 🤔 are they loaded eagerly on cube initialization by the query lib or do they need to be queried separately?

- As dynamic query on observations themselves
  - 👍 accurate ranges/lists based on filtered observations
  - 👎 slower the more observations exist
  - 👍 filters can be applied on the values/labels themselves (e.g. autocomplete)

**Comment by ktk** [comment]
* `sh:in` is a list, if this is returned as array in the API an array `length` should do the trick
* For datasets with really long lists an alternative approach could be to consider [SPARQL-based contstraints](https://www.w3.org/TR/shacl/#sparql-constraints) instead so the lists don't explode. An example is the SSZ name dataset.
* For filters min/max can/should be done in client side

**Comment by ktk** [comment]
The shape provides min/max and `sh:in` lists, both is part of the default pipeline for `cube:Cube`.

**Comment by ktk** [comment]
To clarify: There are min/max values for XSD date/double/float/integer in the shape already (created by the upcoming, generic pipeline for cubes). Not sure what a min/max value would be in geo coordinates. Also geo coordinates would be attached to an outgoing URL, never on the Observation itself due to its nature (lat/long values).

For min/max in fitlers we should address that in the client or in a query-lib, not in the cube itself. So I consider this issue as resolved.

**Comment by jstcki** [comment]
Regarding geo coordinates: do you have an example for such an URL? I think these are just continuous numbers (ie double) in the range from -180 to +180 (lon) and -90 to +90 (lat). Wouldn't it be a bit overkill to have an URL for each possible lon/lat pair in a dataset? Two dimensions of type wgs:lon and wgs:lat would work too?

**Comment by ktk** [comment]
I think I used both models in the past. In the case of BAFU UBD we have stations, a station is a place so you would have something like

```turtle
<agAAR> a schema:Place ;
  schema:name "Aarau" ;
  schema:latitude 47.39444 ;
  schema:longitude 8.05256 ;
```

And then the observation would just point to `<agAAR>`.

That would make sense if there is a limited number of stations and it's really about the station and less about the location.

A counter-example would be weather forecast. It's been a while but IIRC we did directly attach lat/long to the observation in that scenario, as it was on a 1km grid and there is no particular "station" or something alike attached to it. Will think about it again, probably both scenarios are valid, depending on what is represented in the data.

**Comment by Rdataflow** [comment]
@ktk AFAIK in many cases the goal is to store and reuse the geo part (location) in the swisstopo store ld.geo.admin.ch - at least for LFI this is true. Thus the queries via API need to include referred geo parts from ld.geo.admin.ch, however checking of geo constraints (bounding boxes, within boundaries, etc.) should IMHO be done within the swisstopo data integration process - to be verified.

**Comment by ktk** [comment]
@Rdataflow ok that would work in our library already
