### ISSUE TITLE
List of test datasets

### ISSUE THREAD

**Issue by jstcki** [zazuko/rdf-cube-schema-viz#13]
It would be useful to have a list with the test datasets in the new schema. Maybe add a section to the README?

**Comment by ktk** [comment]
# RDF Cube Schema (no or incomplete visualization metadata)
* [Statistik Stadt Zürich](https://s.zazuko.com/rd7nn)

# Complete Visualization-Metadata
* [Elcom Electricity Price](https://s.zazuko.com/2kLiy3) (now contains #6 for municipality/canton, see https://github.com/zazuko/elcom-strompreis/commit/cffea362a373306b2b16bd53c3f6e5046c5d9dd9)
* [SFOE Energy Production](https://s.zazuko.com/jMQPi) - Minimal metadata & simple, flat structure but large time series (`xsd:dateTime`). Use this for testing time filtering over longer periods & resolutions.
  - todo: describe intervals between measurements

**Comment by l00mi** [comment]
@herrstucki with the new datasets online we should be okay to close this. If not please reopen.
