### ISSUE TITLE
Cube attribute: topic(s)

### ISSUE THREAD

**Issue by jstcki** [zazuko/rdf-cube-schema-viz#14]
A cube can be organized by topic, potentially multiple. The topics themselves can be hierarchical.

- So cubes can be filtered by topic

Cf. https://github.com/zazuko/query-rdf-data-cube/issues/53

**Comment by ktk** [comment]
* See #2 #3, should be able to nest them

**Comment by ktk** [comment]
* `dcat:theme`, see [here](https://prefix.zazuko.com/dcat%3Atheme). Range is `skos:Concept`so it can be nested as needed

**Comment by ktk** [comment]
Sample: https://github.com/zazuko/rdf-cube-schema-viz/blob/a5de5d5593e7c499aba4a8534d7b53e184da306e/example/ubd28-static.ttl#L62

**Comment by jstcki** [comment]
@l00mi Is this already fixed conceptually? If yes, this probably needs some documentation.

**Comment by l00mi** [comment]
That is a topic which will be solved per use-case. So for BAFU we will have dcat:theme for the "opendata.swiss" categories: https://s.zazuko.com/uTxGG but further also independently BAFU topics which still need to be defined.

So we will communicate this apart of this documentation which has the goal to be somewhat generic for other use cases here: https://gitlab.ldbar.ch/bafu/umweltdatenkiosk-planning/-/wikis/Dataset-Metadata (will need massive clean-up and restructuring).

**Comment by l00mi** [comment]
This is solved for the Lindas, visualize use case, closing the issue here.
