### ISSUE TITLE
common RDF property to store statistical error per observation

### ISSUE THREAD

**Issue by Rdataflow** [zazuko/rdf-cube-schema-viz#16]
We need a common **RDF Property to store statistical error range (Vertrauensintervall)** per [_observation_](https://github.com/zazuko/rdf-cube-schema/blob/c2aeb1f9f21f157ab51232fa97bc5a64a60a908f/cube.ttl#L62-L64)
and agree on how to expose this information via API to visualize in chart types like that
![image](https://user-images.githubusercontent.com/26090254/95729657-777c1d00-0c7d-11eb-99c8-335fb093e6d7.png)

i.e. Holzvorrat | Kanton GE | Abies alba (Weisstanne) | 10.3 m³/ha | **±10.3 m³/ha**
see table [here](https://www.lfi.ch/resultate/resultate.php?p=reg&zigrNr=21&invNr=450&befNr=2207&regionNr=827&auswNr=434&prodNr=70&prodItNr=869497)

**Comment by ktk** [comment]
That's the same like #15 , closing here.
