### ISSUE TITLE
Cube attribute: scope

### ISSUE THREAD

**Issue by jstcki** [zazuko/rdf-cube-schema-viz#2]
Basically an attribute that describes if the cube can be used with a certain tool. Could also just mean that it's explicit that a cube adheres to **this specific schema**. 

- So compatible tools can filter cubes by their scope/schema

**Comment by ktk** [comment]
* Use some form of tagging/keywords
* Check if there is something available in schema.org or other common vocabs
* Attached directly to cube:Cube

**Comment by ktk** [comment]
I'm thinking about:

* https://schema.org/subjectOf
* and then modeling each application that is using it as https://schema.org/CreativeWork

That seems to work from how I read the descriptions.

**Comment by ktk** [comment]
This seems interesting as well:
* `duv:hasUsage` [spec](https://www.w3.org/TR/vocab-duv/#Usage_Model)
* and an application would be `duv:UsageTool` [spec](https://www.w3.org/TR/vocab-duv/#class-usageTool)

**Comment by l00mi** [comment]
We need to fix this for the first cubes.

I have a preference for schema:workExample with  schema.org/CreativeWork:
1. it is used https://schema.ld.admin.ch/LindasDataset anyway on the dataset for lindas
2. we can add easily the URL (missing in duv:hasUsage it seems)
3. we do not introduce another ontology.

So i propose to add to the DataSet for the two use cases we have currently:

In case of publication for visualize.admin.ch:
`<cube1> schema:workExample <https://ld.admin.ch/application/visualize>.`

In case of publication on opendata.swiss:
`<cube1> schema:workExample <https://ld.admin.ch/application/opendataswiss>.`

**Comment by ktk** [comment]
TBH I can't really figure out a difference between the definition of `subjectOf` and `workExample`, I have a slight preference for `subjectOf` because I dislike the `example` part of the other term but I can live with both.

**Comment by l00mi** [comment]
The biggest difference I see is that `workExample` is used on the type `CreativeWork`, where as `subjectOf` is used on the type `Thing`. Because `Dataset` is a `CreativeWork`, the property `workExample` is more specific in this case.

(Both do expect a type of `CreativeWork`.)
