### ISSUE TITLE
Order of the dimensions

### ISSUE THREAD

**Issue by davidhanimann** [zazuko/rdf-cube-schema-viz#20]
Is there a way to define the order of the dimensions within the data or is this completely up to the data-consuming application? For example when putting the data in a table view, who decides what dimension comes into the first column?

**Comment by l00mi** [comment]
@ktk did you have done this already, i think we had once discussed to go for [shacl:order](https://www.w3.org/TR/shacl/#order) ?

**Comment by ktk** [comment]
On what level would we want to attach it? Within the shape? Then SHACL makes sense. In another project I use https://schema.org/position as well

**Comment by l00mi** [comment]
Yes the property Shape of the dimension would have been my first guess. Shall we define this here in viz or in rdf-cube-schema itself?

**Comment by ktk** [comment]
I would do that in -cube

**Comment by ktk** [comment]
Documented in [this](https://github.com/zazuko/rdf-cube-schema/commit/bc8fe2a5fb4151a9278a5e82601d917e5f2a6a0e) commit.

**Comment by l00mi** [comment]
Not yet in the cube-creator: https://github.com/zazuko/cube-creator/issues/700
