### ISSUE TITLE
Cube name and description is not displayed in dev.visualize.admin

### ISSUE THREAD

**Issue by davidhanimann** [zazuko/rdf-cube-schema-viz#21]
Our cube is described as follows in accordance with the documentation in this repo:  

```sparql
<http://www.wsl.ch/ldlfi/49-96-1266-None/cube> a cube:Cube ;
    schema:description "Example Cube LFI using criteria X,Y,Z"@de ;
    schema:name "Example Cube LFI"@de  .   
```

Name and description are displayed in the cube-viewer however.

**Comment by l00mi** [comment]
As expected visualize does use dc:title right now @herrstucki will change it soon to schema:name and schema:description.

**Comment by jstcki** [comment]
@davidhanimann Currently deploying to https://dev.visualize.admin.ch.

**Comment by davidhanimann** [comment]
> @davidhanimann Currently deploying to https://dev.visualize.admin.ch.

Seems to work! Thanks!
