### ISSUE TITLE
No diagrams are shown in dev.visualize.admin

### ISSUE THREAD

**Issue by davidhanimann** [zazuko/rdf-cube-schema-viz#22]
We don't manage to enable diagrams other than "table" in the visualization tool.   
A MeasureDimension currently looks like this:   
```sparql
[ a cube:MeasureDimension ;
            schema:name "Zielgr targetValue#249"@de ;
            qudt:scaleType ns1:IntervalScale ;
            sh:maxCount 1 ;
            sh:minCount 1 ;
            sh:or [ a rdf:List ;
                    rdf:first [ sh:datatype xsd:double ] ;
                    rdf:rest [ sh:datatype xsd:integer ] ] ;
            sh:path <http://www.wsl.ch/ldlfi/targetValue#249> ]
```

**Comment by l00mi** [comment]
Looking at https://s.zazuko.com/2antAn i think what is missing is sh:in with the list of all entries for NominalScales.

@herrstucki do you see anything else missing? Also might it be a problem that this cubes are not versioned?

**Comment by jstcki** [comment]
I think the mixed datatype of xsd:double and xsd:integer is an issue. The dimension should only have one datatype _or_ one datatype plus `https://cube.link/Undefined`.

Also, we are currently only "looking" for xsd:decimal, xsd:int, xsd:integer. Not sure if other datatypes like float and double even make sense.

**Comment by l00mi** [comment]
@davidhanimann it is absolutely valid what you did it, but that is a (current) constraint from visualize.admin.ch side, which I do not propose to touch right now. I propose to stick to xsd:decimal for mixed dimensions and xsd:integer for purely interger based dimensions.

@herrstucki you might want to add a line to https://dev.visualize.admin.ch/docs# in this regard?

**Comment by jstcki** [comment]
I’m curious about when a mixed datatype would be used. My reasoning is that either it’s a countable dimension (integer) or not (decimal). E.g. just because a temperature can be exactly 0, that doesn’t make it an integer value. 

We can easily support float/double (in the end it’s all the same in JavaScript) but I‘m not sure that it makes sense from a data storage perspective (precision, rounding errors)

**Comment by davidhanimann** [comment]
Completely agreed. Not sure why we did this anyway.
