### ISSUE TITLE
Dimension attribute: unit

### ISSUE THREAD

**Issue by jstcki** [zazuko/rdf-cube-schema-viz#4]
Numerical dimensions should describe their unit. I'm not sure if this should be just any string, e.g. "CHF", "1000 Personen", "kg" or also named types like <ns.example.org/currency/CHF> (with an according schema:name or similar)

- So unit name can be displayed on charts
- So numbers can be formatted automatically (maybe currencies?)

**Comment by ktk** [comment]
* Units should be attached to the shape of the dimension
* All values of a particular dimension should have the same unit
* QUDT if possible
* Check if QUDT has formatting included
* Validate on [UBD28](https://github.com/lindas-uc/bafu_ubd/tree/master/input/ubd/28), which has some nice quirks

**Comment by ktk** [comment]
References:
* [Encoding units and unit types in RDF using QUDT](http://www.openphacts.org/specs/2013/WD-units-20130913/#encoding-units), subsection on _Encoding units_

**Comment by ktk** [comment]
Attached directly to the shape, see here:

https://github.com/zazuko/rdf-cube-schema-viz/blob/7a70503b50c2ada37a9f1b24957680a97482a78d/example/ubd28.ttl#L2880

The unit itself is either taken from QUDT or curated manually, there is a very basic example here:

https://github.com/zazuko/rdf-cube-schema-viz/blob/7a70503b50c2ada37a9f1b24957680a97482a78d/example/ubd28-static.ttl#L5-L6

**Comment by jstcki** [comment]
@ktk Attaching the unit to a dimension seems good to me. Although some obervations (but not all) still have the reference to the unit:

https://github.com/zazuko/rdf-cube-schema-viz/blob/7a70503b50c2ada37a9f1b24957680a97482a78d/example/ubd28.ttl#L21

I assume that's going to go away?

Sidenote: at this point, it's not entirely clear to me what the relation between ubd28.ttl and ubd28-static.ttl is and if this is just a temporary separation or if (and how) this will manifest in a "real" cube.

**Comment by ktk** [comment]
@herrstucki we wanted to show that it can still be attached directly if that is needed. I would not do that in any generated pipelines though.

`ubd28.ttl` is generated from the new pipeline from the original CSV. I had to tweak it a bit as a few things have to be attached directly to the shape. `ubd28-static.ttl` is 100% manually curated and shows what would have to be maintained by the future UI for data curation. If we would load both to a triplestore, we have a complete cube to work with.

**Comment by jstcki** [comment]
Solved via QUDT as described in the README: https://github.com/zazuko/rdf-cube-schema-viz#unit-number-percent-meter-gram-milliter-per-day-
