### ISSUE TITLE
Dimension type: temporal

### ISSUE THREAD

**Issue by jstcki** [zazuko/rdf-cube-schema-viz#8]
Temporal dimensions could be inferred by their data type alone but ideally, there's more information

- period vs. point in time (year, quarter, month, day etc. vs. timestamp)
- time interval (monthly, 3 days, 10 min etc.)

**Comment by ktk** [comment]
- [x] Temporal scale
- [ ] is the first question the question about the duration of a particular period/point in time?
  - if so, we might use [ISO 8601 duration](https://en.wikipedia.org/wiki/ISO_8601#Durations)  directly attached to the shape of the dimension
- [ ] Resolution might be attached directly to the shape

**Comment by ktk** [comment]
Review comment by @vhf in private repo https://github.com/zazuko/cube-ng/pull/5#issuecomment-543028882 and https://github.com/zazuko/cube-ng/pull/5#issuecomment-544390093. Also relevant for #7.

**Comment by ktk** [comment]
https://github.com/zazuko/rdf-cube-schema-viz/blob/532db871aeb61831ae08afc9697a0c7969570e99/vocab/scaleOfMeasure.ttl#L50-L54

Sample usage

https://github.com/zazuko/rdf-cube-schema-viz/blob/532db871aeb61831ae08afc9697a0c7969570e99/example/ubd28.ttl#L1768

**Comment by jstcki** [comment]
Closing in favor of "dataKind" concept https://github.com/zazuko/rdf-cube-schema-viz#datakind-temporal--spatial
