### ISSUE TITLE
Dimension type: ordinal

### ISSUE THREAD

**Issue by jstcki** [zazuko/rdf-cube-schema-viz#9]
Some dimension values need to be ordered consistently. E.g. age groups ("0 – 10", "10 – 20", etc.).

- So a list of dimension values can be displayed in constistent order, e.g. in chart legends

**Comment by ktk** [comment]
* `sh:in` is a list, as long as the data in there is properly ordered this is solved

**Comment by ktk** [comment]
Would be https://github.com/zazuko/rdf-cube-schema-viz/blob/532db871aeb61831ae08afc9697a0c7969570e99/vocab/scaleOfMeasure.ttl#L33-L37

**Comment by l00mi** [comment]
@herrstucki please close if all solved.
